site_name: Xml2db Docs
site_url: https://cre-dev.github.io/xml2db
repo_url: https://github.com/cre-dev/xml2db
repo_name: cre-dev/xml2db
copyright: Copyright &copy; 2024 Commission de régulation de l'énergie
site_description: Xml2db is a Python package to load XML files into a relational database. It handles complex XML and 
  works out of the box, without any custom mapping rules.

nav:
  - Introduction: "index.md"
  - "getting_started.md"
  - "configuring.md"
  - "how_it_works.md"
  - Api:
      - "api/overview.md"
      - "api/data_model.md"
      - "api/document.md"
      - "api/xml_converter.md"

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - navigation.expand
    - toc.follow
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true